{% set name = "trottersuzuki" %}
{% set version = "1.6.2" %}
{% set sha256 = "9f5134c54a9d6b44ed7b0422abb724e295fdcac00f6b94b9da25959be07456d9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url:  https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - osx.patch

build:
  number: 1000
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp                    # [osx]
  host:
    - python
    - pip
    - numpy
    - llvm-openmp                    # [osx]
  run:
    - python
    - numpy
    - llvm-openmp                    # [osx]

test:
  imports:
    - trottersuzuki
  commands:
    - conda inspect linkages -p $PREFIX trottersuzuki  # [not win]
    - conda inspect objects -p $PREFIX trottersuzuki  # [osx]

about:
  home: https://github.com/trotter-suzuki-mpi/trotter-suzuki-mpi
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'Massively Parallel Trotter-Suzuki Solver'
  doc_url: https://trotter-suzuki-mpi.readthedocs.io/
  dev_url: https://github.com/trotter-suzuki-mpi/trotter-suzuki-mpi

extra:
  recipe-maintainers:
    - peterwittek
