# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ge5dREnj3/8tBms4Grl04tiwahNZOUBcD0Ao7idfX9hvab1UoixFKr3RGvrOBcPLTrkgBi2fuTjC19gcsGqP3JWmC6nBu6Nm4sSK1LCf5WHaGoXxAkU2vU0eLS7tW2PzGdv629EwRXdmXsKvqXRNTE3aH8T7PNzH9s03mgzSzxyDj1J25Zj60AL9qvQvPcID6iF3/0S2aOxDtIYQ6J2rqWbxxKKDohnspKm3hknh+fYUinD1U4f5WwtI/Ej3pJdKI2ww1Nwn/7vX5c2f5lL4sf/45aW/Qa1TxZTn3nTGL/RaVdaBGYUwMYGob5P6e50WCtpiuFDkKaiw+VWe91Lw/yztgJCSzqFGq7vL2Tg2D22Vmr1urxXvONQzMCIGsv43LxhnF2MydwiYTK557HYYiVmimGOh6KIwg5izhKPSlcvOFZX4oiZo9MLDxkx8zCsqZeIDLbWUCxxG1OrPlI2MdOrlVETTiTZP4WIG5iImvOByq/ucPQG6eaVDcaebhuW3HxoMy5g/CttQbxBOlGlo0OBiBhBlaKCIojjfPGVl78PWrQvuY3b6NvABrLaKed6vf1LgnB+oTRD69hR+BVmVet+/YRTGVSatNcK4qwK9ySdyCEV1VC9zmn0A7RBVjXTjXu0auTKkT4uBdqtIouT4UyAr3mi4dQcee0kc1kdP8DM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
