# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ge5dREnj3/8tBms4Grl04tiwahNZOUBcD0Ao7idfX9hvab1UoixFKr3RGvrOBcPLTrkgBi2fuTjC19gcsGqP3JWmC6nBu6Nm4sSK1LCf5WHaGoXxAkU2vU0eLS7tW2PzGdv629EwRXdmXsKvqXRNTE3aH8T7PNzH9s03mgzSzxyDj1J25Zj60AL9qvQvPcID6iF3/0S2aOxDtIYQ6J2rqWbxxKKDohnspKm3hknh+fYUinD1U4f5WwtI/Ej3pJdKI2ww1Nwn/7vX5c2f5lL4sf/45aW/Qa1TxZTn3nTGL/RaVdaBGYUwMYGob5P6e50WCtpiuFDkKaiw+VWe91Lw/yztgJCSzqFGq7vL2Tg2D22Vmr1urxXvONQzMCIGsv43LxhnF2MydwiYTK557HYYiVmimGOh6KIwg5izhKPSlcvOFZX4oiZo9MLDxkx8zCsqZeIDLbWUCxxG1OrPlI2MdOrlVETTiTZP4WIG5iImvOByq/ucPQG6eaVDcaebhuW3HxoMy5g/CttQbxBOlGlo0OBiBhBlaKCIojjfPGVl78PWrQvuY3b6NvABrLaKed6vf1LgnB+oTRD69hR+BVmVet+/YRTGVSatNcK4qwK9ySdyCEV1VC9zmn0A7RBVjXTjXu0auTKkT4uBdqtIouT4UyAr3mi4dQcee0kc1kdP8DM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
