travis:
  secure:
    BINSTAR_TOKEN: ge5dREnj3/8tBms4Grl04tiwahNZOUBcD0Ao7idfX9hvab1UoixFKr3RGvrOBcPLTrkgBi2fuTjC19gcsGqP3JWmC6nBu6Nm4sSK1LCf5WHaGoXxAkU2vU0eLS7tW2PzGdv629EwRXdmXsKvqXRNTE3aH8T7PNzH9s03mgzSzxyDj1J25Zj60AL9qvQvPcID6iF3/0S2aOxDtIYQ6J2rqWbxxKKDohnspKm3hknh+fYUinD1U4f5WwtI/Ej3pJdKI2ww1Nwn/7vX5c2f5lL4sf/45aW/Qa1TxZTn3nTGL/RaVdaBGYUwMYGob5P6e50WCtpiuFDkKaiw+VWe91Lw/yztgJCSzqFGq7vL2Tg2D22Vmr1urxXvONQzMCIGsv43LxhnF2MydwiYTK557HYYiVmimGOh6KIwg5izhKPSlcvOFZX4oiZo9MLDxkx8zCsqZeIDLbWUCxxG1OrPlI2MdOrlVETTiTZP4WIG5iImvOByq/ucPQG6eaVDcaebhuW3HxoMy5g/CttQbxBOlGlo0OBiBhBlaKCIojjfPGVl78PWrQvuY3b6NvABrLaKed6vf1LgnB+oTRD69hR+BVmVet+/YRTGVSatNcK4qwK9ySdyCEV1VC9zmn0A7RBVjXTjXu0auTKkT4uBdqtIouT4UyAr3mi4dQcee0kc1kdP8DM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
