travis:
  secure:
    BINSTAR_TOKEN: CFJa/v9guYminazBZW5KwXn7pejk2uTcI7uOl8v6LuJCXeuZWTKTEjWbXy/XUaw2fHAMJs9bMeX7MK+8GcGPPE5QG+74B/4z2CWM8vihezAgrQTdO4fq63LfQn2YX7WEdMjr5M5mMR+mFqJXPzOR+1fCcZO9LiG1osZ1rhnaQOXf0eEyS8TW4/XLhFoJtAsdrTL6JZDisuAQG1Fwer9roXXrroO39YXZYMZJrfjjVNMYBhOe6uDMdbVFp5mrt/NqAjfzG6cL64pDMW5Pea0pLTzXHWyv4JCaOggB0ZaDajk968ATkzUOCpQUHNM8kXge+OmEGlkccAbI9gUcc6E1iiKgcRlXxsM0Y2K/t2jwsN8djHXVlUSXgagaVgPjTy3l9o7oxdhJpab0y/iZTgbeWiKgLVMqrjCrg0Uae2iVpdoEE6JA9j6Z8kkj/yVKC3TM+kwnUeGgf7SZXY8HjvOL5q/pyAyde7x0NsSMewQfE1KWPLU4lmrRZd0IVk9TOEfskFFBMpPDPfsu5aOtGTLGBEYIpaaG0oDbha2RsNDREGFQJPdYw/P6QR7brmTu3YqKhscv/O0Ah8uGixBl6fii9btMccSlXIIMDXCu3SKrGR7GdggDP/LN+BYVk+NFymJr4c2fy2vC+gXo2bIT78JL/inSX0XB8bcSpAohlwVTcDE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
