travis:
  secure:
    BINSTAR_TOKEN: YWrBnPCISCKcdbLl22RXGiQae5hSIzB5V0pv6tINz1T/QliOHqJxyefTdh/K7jYUEYakXtgcK1CnG5f0kGC3j0ObU/uDPnYzUJ1oXHGPPMB7RvOtUthrwDJ909tX0oapqBHRR3VcvfOqQp0Pe09OFcFO7U4X96jszZVSSYNA3dGXukzldHVvOtZPUOZBTKzcanvuaGIstfNNi25pCzXFvc4Cnk3Yd0BEGCxGMVFPZo1jaFB66ToJ5XAFoXKJHrO1cBFVJy2dA0MOG07jZZrz5J29AABcgYoMAZsN4A9PGnBQRgOg/TBdizRuxuK2SmA+AZdQqd5Rsh+1Rz5UZwcATFgCK7j6lDBv/pdKqc1/rZxkRGK/A2188rXLdcV1CjM6cKyf25Q1mX5Vd+JiPa6rHyxmdVU5c6PXDHUOEi8BT4bfKX3STo6VnQpp6QjCZZ/+QtClHzbkc2ylC7Hy4lw2ktGMoqZK17laPZS7ZdPo7CM4vMsOstPcfsBkYyADR/doPiczPwctjgvuHUavY4Vzbb+qvOp/jghQd5f8ffqB8yKvusrz05P9zfi+t/xTM76v+36PKRCqK+YapQtrHFY2JJJrlLkiaSHPdFC0kpUHD4lKKZi8Xop+Qg3dfpYRZf4Pf8qgwcyj6LG9CPs0APTyoOj9xdGyIYyhqwqeMn1ob6A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
