travis:
  secure:
    BINSTAR_TOKEN: JTdkc4ajW0h7x7KWODuRKJ/BaUZ7B2//eelAxiEhs6Ho1SldDJxcU7KzvND6XwB0xqp8BTgOmSa3vOA4Lrkqtnj3EeXYwSia9LtnW1k1suXuctqgMkGSiVLa915WTQ1bgK8yiqJu2DCKAlwwptRfW4//XzVwwAQVRnmU0Al9tQFUig+neUXwIMfGkfPMcga2AZkkRnaQAbx+tT/9b/JtFToDnnj8UOZIvS2YYY54f6e7vcJW8ps5b58T4Tk9YJJUfai+v37jFkqbHPHVMiD9miiBdmB3Ymz+PozkxHmvW32mvqhUM/jRe73UbcLC9YcGmcBeenI2hqihnYgv9/GoFisMMXNvHxD/6+NHJDW1KBqPQfzcNleeJz8YYS4YIc9PPc4MlBay/lIkq3YuF22WR+URPEx2oKpibHWSX/dJPMfuLUafHJMW0+rp8I/s9M83/QwubtFXG5iNTyi1qvg1Y5CQ5BDDw5z984uzrSk7XLtdNiyh0BF4bDWgzM2E2SlUTq1cStppG2X/b77KcupLlofP6053ijtcMsHkMSBUnxyR6thmfWvCyGeiZlAdA3MNeI92jD1fu5GHLdHphKvxkaluV9vWxCtFgt055LNtJTUr0QT8oiZAq/BsMNuaMb7pRXpiwtsrO+ypRD0kdTs4Fx8v/ZYnStoJ0lKM9EUX8fY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
